on: push
jobs:
  build-packages:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run make -- --platform darwin
      # log changed files
      - run: git diff --name-only HEAD^
      # stage and commit changed files
      - name: Stage changed files
        run: git add .
      - name: Commit changed files
        run: git commit -m "Generated build"
      